[build]
  command = "npm install autoprefixer postcss tailwindcss && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_ASSET_PREFIX = "."

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/@next/swc-linux-x64-gnu/**/*",
    "node_modules/autoprefixer/**/*",
    "node_modules/postcss/**/*",
    "node_modules/tailwindcss/**/*"
  ]
